# Generated by Django 3.2.4 on 2021-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_podcast_name_uploads_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='mp3',
            field=models.FileField(upload_to='static'),
        ),
    ]
