# Generated by Django 3.2.4 on 2021-06-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_uploads_mp3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='mp3',
            field=models.FileField(upload_to=''),
        ),
    ]
