# Generated by Django 3.1.8 on 2021-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_uploads_mp3'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mp3', models.FileField(default='media', upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mp4', models.FileField(default='media', upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='uploads',
        ),
    ]
